export const GYM_EXERCISE_DATA: { name: string; muscle_group: string; split_category: string; description: string; safety_guide: string }[] = [
  { name: "Flat Barbell Bench Press", muscle_group: "Chest", split_category: "Push / Upper", description: 'The "king" of horizontal presses.', safety_guide: "Keep feet flat; don't bounce the bar." },
  { name: "Incline Dumbbell Press", muscle_group: "Chest", split_category: "Push / Upper", description: "Targets the clavicular head (upper chest).", safety_guide: "Bench at 30-45°; tuck elbows." },
  { name: "Low-to-High Cable Fly", muscle_group: "Chest", split_category: "Push / Upper", description: "Focuses on the upper/inner chest stretch.", safety_guide: "Maintain a slight, fixed elbow bend." },
  { name: "Chest-Focused Dips", muscle_group: "Chest", split_category: "Push / Upper", description: "Vertical press with a 30° forward lean.", safety_guide: "Don't go deeper than shoulder comfort." },
  { name: "Pec Deck Machine", muscle_group: "Chest", split_category: "Push / Upper", description: "Maximum isolation/contraction for pec mass.", safety_guide: "Align handles with mid-chest height." },
  { name: "High-to-Low Cable Fly", muscle_group: "Chest", split_category: "Push / Upper", description: "Emphasizes the lower (sternal) pecs.", safety_guide: "Squeeze handles together at the bottom." },
  { name: "Hammer Strength Press", muscle_group: "Chest", split_category: "Push / Upper", description: "Machine press for stable, heavy loading.", safety_guide: "Sit deep in seat; avoid shoulder shrugging." },
  { name: "Floor Press (Dumbbell)", muscle_group: "Chest", split_category: "Push / Upper", description: "Limits range to protect shoulders.", safety_guide: "Keep elbows at 45° to the body." },
  { name: "Landmine Press", muscle_group: "Chest", split_category: "Push / Upper", description: "Angled press great for shoulder health.", safety_guide: "Stand tall; don't lean back as you press." },
  { name: "Deficit Push-ups", muscle_group: "Chest", split_category: "Push / Upper", description: "Using blocks for a deeper chest stretch.", safety_guide: "Maintain a rigid core; don't let hips sag." },
  { name: "Decline Barbell Press", muscle_group: "Chest", split_category: "Push / Upper", description: "Targets the lower pecs heavily.", safety_guide: "Use a spotter; be careful with the rack." },
  { name: "Plate Squeeze Press", muscle_group: "Chest", split_category: "Push / Upper", description: "Squeezing a plate while pressing.", safety_guide: 'High "mind-muscle" move; go slow.' },
  { name: "Smith Machine Incline", muscle_group: "Chest", split_category: "Push / Upper", description: "Fixed path for high-volume upper chest.", safety_guide: 'Great for slow-tempo "stretch" reps.' },
  { name: "Dumbbell Pullover", muscle_group: "Chest", split_category: "Push / Upper", description: "Lowering weight behind head for lats/pecs.", safety_guide: "Keep hips low; stop when arms are overhead." },
  { name: "Converging Machine Fly", muscle_group: "Chest", split_category: "Push / Upper", description: "Arcs inward for peak inner-chest tension.", safety_guide: 'Focus on the "squeeze" in the center.' },
  { name: "Weighted Push-ups", muscle_group: "Chest", split_category: "Push / Upper", description: "Classic push-up with a plate on back.", safety_guide: "Ensure plate is centered on upper back." },
  { name: "Single-Arm Cable Press", muscle_group: "Chest", split_category: "Push / Upper", description: "Unilateral work for chest symmetry.", safety_guide: "Use core to resist twisting (anti-rotation)." },
  { name: "Incline Fly (Dumbbell)", muscle_group: "Chest", split_category: "Push / Upper", description: "Stretching the upper chest at 45°.", safety_guide: 'Use light weights; focus on the "pull."' },
  { name: "Close-Grip Bench Press", muscle_group: "Chest", split_category: "Push / Upper", description: "Targets inner chest and triceps.", safety_guide: "Don't let elbows flare out too far." },
  { name: "Plyometric Push-ups", muscle_group: "Chest", split_category: "Push / Upper", description: "Explosive power for chest fibers.", safety_guide: "Land with soft, absorbing elbows." },
  { name: "Conventional Deadlift", muscle_group: "Back", split_category: "Pull / Lower", description: "Power move for the entire posterior chain.", safety_guide: "Flat back; bar must travel up the shins." },
  { name: "Wide-Grip Pull-up", muscle_group: "Back", split_category: "Pull / Upper", description: "The gold standard for back width.", safety_guide: "Pull chest to bar; don't swing legs." },
  { name: "Seated Cable Row", muscle_group: "Back", split_category: "Pull / Upper", description: "Horizontal pull for mid-back thickness.", safety_guide: "Keep chest up; pull with elbows." },
  { name: "Chest-Supported Row", muscle_group: "Back", split_category: "Pull / Upper", description: "Eliminates momentum for strict rowing.", safety_guide: "Breathe out as you pull; don't lift chest." },
  { name: "One-Arm Dumbbell Row", muscle_group: "Back", split_category: "Pull / Upper", description: "Unilateral move for back balance.", safety_guide: "Back parallel to floor; avoid spinal twist." },
  { name: "Lat Pulldown", muscle_group: "Back", split_category: "Pull / Upper", description: "Machine alternative to the pull-up.", safety_guide: "Lean back slightly; pull to upper chest." },
  { name: "T-Bar Row (Landmine)", muscle_group: "Back", split_category: "Pull / Upper", description: "Old-school heavy mid-back move.", safety_guide: "Keep knees bent; avoid lower back rounding." },
  { name: "Pendlay Row", muscle_group: "Back", split_category: "Pull / Upper", description: "Strict row from floor for explosive power.", safety_guide: "Reset on the floor between every rep." },
  { name: "Face Pulls", muscle_group: "Back", split_category: "Pull / Upper", description: "Targets rear delts and upper traps.", safety_guide: "Pull rope to ears; rotate hands outward." },
  { name: "Straight-Arm Pulldown", muscle_group: "Back", split_category: "Pull / Upper", description: "Lat isolation without bicep help.", safety_guide: 'Imagine "scooping" the weight down.' },
  { name: "Meadows Row", muscle_group: "Back", split_category: "Pull / Upper", description: "Single-arm overhand row (landmine).", safety_guide: "Use a staggered stance for stability." },
  { name: "Seal Row", muscle_group: "Back", split_category: "Pull / Upper", description: "Lying on high bench, rowing upward.", safety_guide: "Maximum back isolation; saves the spine." },
  { name: "Rack Pulls", muscle_group: "Back", split_category: "Pull / Upper", description: "Partial deadlift for trap/back mass.", safety_guide: "Start bar just above or below the knees." },
  { name: "Inverted Row", muscle_group: "Back", split_category: "Pull / Upper", description: "Bodyweight horizontal row.", safety_guide: "Keep body in a straight line (heels to head)." },
  { name: "Kneeling 1-Arm Pulldown", muscle_group: "Back", split_category: "Pull / Upper", description: "Deep stretch for the lower lat fibers.", safety_guide: "Reach high at the top for maximum stretch." },
  { name: "Barbell Shrugs", muscle_group: "Back", split_category: "Pull / Upper", description: "Isolation for the upper trapezius.", safety_guide: "Lift shoulders toward ears; don't roll them." },
  { name: "Back Extensions", muscle_group: "Back", split_category: "Pull / Lower", description: "Targets lower back and hamstrings.", safety_guide: "Cross arms; don't overextend the spine." },
  { name: "Kettlebell Swings", muscle_group: "Back", split_category: "Pull / Lower", description: "Explosive hip hinge for back power.", safety_guide: "Hinge at hips; don't use arms to lift weight." },
  { name: "Bent-Over Barbell Row", muscle_group: "Back", split_category: "Pull / Upper", description: "Heavy compound horizontal pull.", safety_guide: "Torso at 45°; engage core deeply." },
  { name: "Helms Row", muscle_group: "Back", split_category: "Pull / Upper", description: "Row leaning on an incline bench.", safety_guide: "Prevents lower-back strain during heavy pulls." },
  { name: "Overhead Press (Barbell)", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Pure overhead pressing power.", safety_guide: "Squeeze glutes to protect lower back." },
  { name: "Dumbbell Lateral Raise", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Targets the side delts for width.", safety_guide: "Lead with elbows; keep hands below elbows." },
  { name: "Arnold Press", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Rotation press for all 3 delt heads.", safety_guide: "Rotate weights smoothly near the face." },
  { name: "Seated Dumbbell Press", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Stable overhead press for mass.", safety_guide: "Keep back pressed against the seat pad." },
  { name: "Reverse Pec Deck", muscle_group: "Shoulders", split_category: "Pull / Upper", description: "Rear delt isolation machine.", safety_guide: "Don't let weights touch to keep tension." },
  { name: "Cable Lateral Raise", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Constant tension side delt move.", safety_guide: "Cross cable in front of body for stretch." },
  { name: "Upright Row (Wide)", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Targets side delts and upper traps.", safety_guide: "Keep bar close; stop at mid-chest level." },
  { name: "Front Plate Raise", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Targets front delts specifically.", safety_guide: "Control the descent; don't swing torso." },
  { name: "Egyptian Lateral Raise", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Leaning cable raise for deep stretch.", safety_guide: "Grip a post for a 30° lean away." },
  { name: "Lu Raises", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Full ROM raise (to overhead).", safety_guide: "Use light weights; focus on scapular control." },
  { name: "Plate Bus Drivers", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Front delt stability and rotation.", safety_guide: "Keep arms parallel to floor; move slowly." },
  { name: "Push Press", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Power press with leg assistance.", safety_guide: "Drive with legs; lockout at the top." },
  { name: "Bent-Over Rear Fly", muscle_group: "Shoulders", split_category: "Pull / Upper", description: "Standing rear delt flyes.", safety_guide: "Keep neck neutral; don't look up at mirror." },
  { name: "Z-Press", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Pressing sitting on the floor.", safety_guide: "Eliminates leg drive; forces core stability." },
  { name: "Cuban Press", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Rotator cuff and shoulder stability.", safety_guide: "Use very light weights; focus on rotation." },
  { name: "Dumbbell Scaption", muscle_group: "Shoulders", split_category: "Push / Upper", description: 'Raising weights in a "Y" shape.', safety_guide: "Healthiest path for the shoulder joint." },
  { name: "Landmine 1-Arm Press", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Unilateral angled press.", safety_guide: "Good for those with limited shoulder ROM." },
  { name: "High Pull (Landmine)", muscle_group: "Shoulders", split_category: "Pull / Upper", description: "Explosive pull to mid-chest.", safety_guide: "Powerful move for traps and rear delts." },
  { name: "Overhead Face Pull", muscle_group: "Shoulders", split_category: "Pull / Upper", description: "Pulling high cable to the chin.", safety_guide: "Squeeze shoulder blades at the finish." },
  { name: "External Cable Rotation", muscle_group: "Shoulders", split_category: "Push / Upper", description: "Rotator cuff health and stability.", safety_guide: "Keep elbow pinned to your side with a towel." },
  { name: "Barbell Back Squat", muscle_group: "Legs", split_category: "Legs / Lower", description: "The ultimate leg builder.", safety_guide: 'Sit "into" hips; keep knees tracking over toes.' },
  { name: "Romanian Deadlift", muscle_group: "Legs", split_category: "Legs / Lower", description: "Lengthened-position hamstring mass.", safety_guide: "Push hips back; stop when back starts rounding." },
  { name: "Leg Press", muscle_group: "Legs", split_category: "Legs / Lower", description: "Compound move with lower back support.", safety_guide: "Don't lock knees; don't let lower back lift." },
  { name: "Bulgarian Split Squat", muscle_group: "Legs", split_category: "Legs / Lower", description: "Brutal unilateral quad/glute move.", safety_guide: "Keep front shin vertical for glute focus." },
  { name: "Hack Squat Machine", muscle_group: "Legs", split_category: "Legs / Lower", description: "Machine squat for quad isolation.", safety_guide: "Lower until thighs are parallel to footplate." },
  { name: "Leg Extensions", muscle_group: "Legs", split_category: "Legs / Lower", description: "Isolation for the quadriceps.", safety_guide: "Control the weight; don't kick it up." },
  { name: "Lying Leg Curl", muscle_group: "Legs", split_category: "Legs / Lower", description: "Isolation for hamstring thickness.", safety_guide: "Keep hips on the pad; don't arch back." },
  { name: "Barbell Hip Thrust", muscle_group: "Legs", split_category: "Legs / Lower", description: "Number one move for glute mass.", safety_guide: "Tuck chin; squeeze glutes hard at the top." },
  { name: "Goblet Squat", muscle_group: "Legs", split_category: "Legs / Lower", description: "Weighted squat with front load.", safety_guide: "Great for core and upright posture." },
  { name: "Walking Lunges", muscle_group: "Legs", split_category: "Legs / Lower", description: "Dynamic movement for overall legs.", safety_guide: "Take long steps; keep torso upright." },
  { name: "Stiff-Leg Deadlift", muscle_group: "Legs", split_category: "Legs / Lower", description: "Maximum hamstring stretch move.", safety_guide: "Use a slow eccentric (lowering) phase." },
  { name: "Glute-Ham Raise", muscle_group: "Legs", split_category: "Legs / Lower", description: "Hardest bodyweight leg move.", safety_guide: "Keep a straight line from knees to head." },
  { name: "Seated Calf Raise", muscle_group: "Legs", split_category: "Legs / Lower", description: "Targets the soleus (lower calf).", safety_guide: "Hold the stretch at the bottom for 1 sec." },
  { name: "Standing Calf Raise", muscle_group: "Legs", split_category: "Legs / Lower", description: "Targets the gastrocnemius (upper calf).", safety_guide: "Push through the big toe; don't bounce." },
  { name: "Nordic Hamstring Curl", muscle_group: "Legs", split_category: "Legs / Lower", description: "High-tension eccentric builder.", safety_guide: "Lower your torso as slowly as possible." },
  { name: "Box Step-ups", muscle_group: "Legs", split_category: "Legs / Lower", description: "Unilateral quad and glute move.", safety_guide: "Don't push off the floor with the back foot." },
  { name: "Sissy Squat", muscle_group: "Legs", split_category: "Legs / Lower", description: "Intense quad isolation (stretch).", safety_guide: "Lean back with knees forward; use a rack for support." },
  { name: "Barbell Good Morning", muscle_group: "Legs", split_category: "Legs / Lower", description: "Hip hinge with bar on upper back.", safety_guide: "Keep knees slightly bent; focus on hamstrings." },
  { name: "Glute Kickbacks (Cable)", muscle_group: "Legs", split_category: "Legs / Lower", description: "Targeted isolation for the glutes.", safety_guide: "Move only the leg; don't swing the torso." },
  { name: "Leg Press Calf Raise", muscle_group: "Legs", split_category: "Legs / Lower", description: "Heavy calf press on the machine.", safety_guide: "Balls of feet on the bottom edge; full stretch." },
  { name: "Barbell Bicep Curl", muscle_group: "Arms", split_category: "Pull / Upper", description: "Classic mass builder for biceps.", safety_guide: "Don't swing; keep elbows at your sides." },
  { name: "EZ-Bar Skullcrusher", muscle_group: "Arms", split_category: "Push / Upper", description: "Heavy tricep long-head movement.", safety_guide: "Lower bar to forehead; keep elbows in." },
  { name: "Incline Dumbbell Curl", muscle_group: "Arms", split_category: "Pull / Upper", description: "Maximizes bicep stretch (lengthened).", safety_guide: "Keep arms behind the torso throughout." },
  { name: "Triceps Rope Pushdown", muscle_group: "Arms", split_category: "Push / Upper", description: "Constant tension for lateral head.", safety_guide: "Spread the rope at the bottom; squeeze." },
  { name: "Hammer Curls", muscle_group: "Arms", split_category: "Pull / Upper", description: "Targets brachialis and forearms.", safety_guide: "Neutral grip (palms in); no body momentum." },
  { name: "Close-Grip Bench Press (Arms)", muscle_group: "Arms", split_category: "Push / Upper", description: "Tricep mass with chest support.", safety_guide: "Keep hands shoulder-width apart." },
  { name: "Preacher Curl", muscle_group: "Arms", split_category: "Pull / Upper", description: "Eliminates cheating for bicep peaks.", safety_guide: "Don't fully lock elbows at the bottom." },
  { name: "Overhead Cable Extension", muscle_group: "Arms", split_category: "Push / Upper", description: "Targets tricep long head in stretch.", safety_guide: "Pull cable up and over head; elbows high." },
  { name: "Concentration Curl", muscle_group: "Arms", split_category: "Pull / Upper", description: "Peak-contraction bicep move.", safety_guide: "Elbow against inner thigh; rotate pinky up." },
  { name: "Triceps Dips (Upright)", muscle_group: "Arms", split_category: "Push / Upper", description: "Heavy compound for tricep mass.", safety_guide: "Keep body vertical; elbows close to sides." },
  { name: "Bayesian Cable Curl", muscle_group: "Arms", split_category: "Pull / Upper", description: "Facing away from cable for stretch.", safety_guide: "2026 science-based favorite for growth." },
  { name: "Cable Triceps Kickback", muscle_group: "Arms", split_category: "Push / Upper", description: "Isolation for the medial head.", safety_guide: 'Use a slow, controlled "hold" at the end.' },
  { name: "Spider Curls", muscle_group: "Arms", split_category: "Pull / Upper", description: "Chest-down on incline bench.", safety_guide: "Hardest at the top; maximum bicep tension." },
  { name: "Diamond Push-ups", muscle_group: "Arms", split_category: "Push / Upper", description: "Bodyweight tricep/inner chest move.", safety_guide: "Form a triangle with hands; tuck elbows." },
  { name: "Cross-Body Hammer Curl", muscle_group: "Arms", split_category: "Pull / Upper", description: "Targets brachialis and outer bicep.", safety_guide: "Curl weight toward the opposite shoulder." },
  { name: "Bench Dips", muscle_group: "Arms", split_category: "Push / Upper", description: "Tricep isolation using a bench.", safety_guide: "Keep back close to bench; don't roll forward." },
  { name: "Zottman Curl", muscle_group: "Arms", split_category: "Pull / Upper", description: "Bicep/forearm hybrid move.", safety_guide: "Palms up on way up, palms down on way down." },
  { name: "JM Press", muscle_group: "Arms", split_category: "Push / Upper", description: "Hybrid bench and skullcrusher.", safety_guide: "Lower bar toward chin; press up explosively." },
  { name: "Waiter Curls", muscle_group: "Arms", split_category: "Pull / Upper", description: 'Targets the bicep "peak" short head.', safety_guide: "Hold one dumbbell head with both palms." },
  { name: "Tate Press", muscle_group: "Arms", split_category: "Push / Upper", description: "Dumbbell tricep move (inward).", safety_guide: "Focus on the elbow hinge; great for stability." },
  { name: "Cable Crunch", muscle_group: "Core", split_category: "Core / Lower", description: "Weighted upper ab development.", safety_guide: 'Crunch "down and in"; don\'t sit back on heels.' },
  { name: "Hanging Leg Raise", muscle_group: "Core", split_category: "Core / Lower", description: "Advanced lower ab movement.", safety_guide: "Avoid swinging; lift hips toward ribs." },
  { name: "Ab Wheel Rollout", muscle_group: "Core", split_category: "Core / Lower", description: "Anti-extension core strength.", safety_guide: "Keep lower back slightly rounded; core tight." },
  { name: "Weighted Plank", muscle_group: "Core", split_category: "Core / Lower", description: "Isometric endurance with load.", safety_guide: "Maintain a straight line; don't let back sag." },
  { name: "Russian Twist", muscle_group: "Core", split_category: "Core / Lower", description: "Oblique rotation mass.", safety_guide: "Move your ribcage, not just your hands." },
  { name: "Dragon Flag", muscle_group: "Core", split_category: "Core / Lower", description: "Elite-level full-core movement.", safety_guide: "Lower body as one unit; keep legs straight." },
  { name: "Cable Woodchopper", muscle_group: "Core", split_category: "Core / Lower", description: "Rotational power for obliques.", safety_guide: "Pivot on the back foot; pull across body." },
  { name: "Bicycle Crunch", muscle_group: "Core", split_category: "Core / Lower", description: "High-rep burner for all ab heads.", safety_guide: "Touch elbow to opposite knee slowly." },
  { name: "Deadbug (Weighted)", muscle_group: "Core", split_category: "Core / Lower", description: "Deep core stability (transverse).", safety_guide: "Slow movement; keep back pinned to floor." },
  { name: "Pallof Press", muscle_group: "Core", split_category: "Core / Lower", description: "Anti-rotation core stability.", safety_guide: "Push cable forward; resist side-pull." },
  { name: "V-Ups", muscle_group: "Core", split_category: "Core / Lower", description: "Compound upper/lower ab move.", safety_guide: "Meet hands and toes at the center." },
  { name: "Reverse Crunch", muscle_group: "Core", split_category: "Core / Lower", description: "Isolation for the lower abs.", safety_guide: "Focus on rolling your pelvis toward chest." },
  { name: "Bird Dog", muscle_group: "Core", split_category: "Core / Lower", description: "Core and lower back stability.", safety_guide: "Raise opposite arm/leg; hold for 3 sec." },
  { name: "Captain's Chair Raise", muscle_group: "Core", split_category: "Core / Lower", description: "Stable leg raise alternative.", safety_guide: "Press back against pad; control the drop." },
  { name: "Serratus Crunch", muscle_group: "Core", split_category: "Core / Lower", description: 'Targets the "rib" muscles/abs.', safety_guide: "Reach for the ceiling with a light plate." },
  { name: "L-Sit Hold", muscle_group: "Core", split_category: "Core / Lower", description: "Static strength on floor/bars.", safety_guide: "Lock elbows; keep legs parallel to floor." },
  { name: "Windshield Wipers", muscle_group: "Core", split_category: "Core / Lower", description: "Advanced oblique/lateral move.", safety_guide: "Rotate legs side-to-side while hanging." },
  { name: "Mountain Climbers", muscle_group: "Core", split_category: "Core / Lower", description: "Dynamic core and cardio move.", safety_guide: "Drive knees in fast; keep hips level." },
  { name: "Stir the Pot", muscle_group: "Core", split_category: "Core / Lower", description: "Plank circles on stability ball.", safety_guide: "Small, controlled circles for maximum burn." },
  { name: "Side Plank Hip Dips", muscle_group: "Core", split_category: "Core / Lower", description: "Oblique and lateral chain focus.", safety_guide: "Keep body in a straight vertical plane." },
];
